# Generated by Django 5.1.3 on 2024-11-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpp', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Product_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpp.product'),
            preserve_default=False,
        ),
    ]
