# Generated by Django 5.1.3 on 2024-11-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpp', '0003_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
