# Generated by Django 5.1.3 on 2024-11-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpp', '0004_remove_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product_Id',
            new_name='product',
        ),
    ]
