# Generated by Django 5.1.3 on 2024-11-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpp', '0005_rename_product_id_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
    ]
